services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: dopkanji:prod
    container_name: dopkanji-prod
    restart: unless-stopped
    environment:
      NODE_ENV: production
      NITRO_HOST: 0.0.0.0
      NITRO_PORT: 3000
    ports:
      - "3000:3000"
